"""Builds CSV/Excel Output downloads in memory for the browser — see
frontend/static/js/nodes/tableExport.js for how tables are assembled before
POSTing here. Nothing is written to the server filesystem; the routes in
backend/routes/dx_routes.py stream the bytes back as attachment downloads.

Headless export scripts generated by flow_codegen.py still write files
locally on the machine where the script runs.
"""

import csv
import io
import os
import re
import zipfile

from openpyxl import Workbook


def _safe_filename_part(text):
    """Sanitizes one filename component — same allowlist as FlowService._path_for."""
    return re.sub(r'[^a-zA-Z0-9_-]', '', text or '') or 'export'


def _download_basename(filepath, node_id, extension):
    """Turns the node's optional path/filename field into a safe download
    basename only — directory segments are stripped so a saved flow can't
    steer the server toward an arbitrary filesystem path.
    """
    raw = (filepath or '').strip()
    if raw:
        name = os.path.basename(raw)
        if not name.lower().endswith(extension):
            name += extension
        stem, ext = os.path.splitext(name)
        safe_stem = _safe_filename_part(stem)
        return f'{safe_stem}{ext or extension}'
    return f'{_safe_filename_part(node_id)}{extension}'


def _insert_suffix(path, suffix):
    base, ext = os.path.splitext(path)
    return f'{base}_{_safe_filename_part(suffix)}{ext}'


def render_csv_bytes(table):
    """One `{columns, rows}` table → UTF-8 CSV bytes."""
    buffer = io.StringIO()
    writer = csv.writer(buffer)
    writer.writerow(table['columns'])
    writer.writerows(table['rows'])
    return buffer.getvalue().encode('utf-8')


def render_excel_bytes(tables):
    """Every table → one sheet in a single .xlsx workbook (in memory)."""
    workbook = Workbook()
    workbook.remove(workbook.active)
    used_names = set()
    for table in tables:
        sheet = workbook.create_sheet(title=_sheet_name(table['name'], used_names))
        sheet.append(table['columns'])
        for row in table['rows']:
            sheet.append(row)

    buffer = io.BytesIO()
    workbook.save(buffer)
    return buffer.getvalue()


def _sheet_name(name, used_names):
    cleaned = re.sub(r'[\[\]:*?/\\]', '_', name or 'Sheet')[:31] or 'Sheet'
    candidate = cleaned
    index = 2
    while candidate in used_names:
        candidate = f'{cleaned[:28]}_{index}'
        index += 1
    used_names.add(candidate)
    return candidate


def build_csv_download(tables, filepath, node_id):
    """Returns `(payload_bytes, download_filename, mimetype)` for a CSV export.

    One table shape → a single `.csv` file. Several distinct table shapes →
    one `.zip` containing a CSV per shape (same idea as the old multi-file
    disk export, but delivered as one browser download).
    """
    if not tables:
        return None, None, None

    basename = _download_basename(filepath, node_id, '.csv')

    if len(tables) == 1:
        return render_csv_bytes(tables[0]), basename, 'text/csv; charset=utf-8'

    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
        for table in tables:
            entry_name = _insert_suffix(basename, table['name'])
            archive.writestr(entry_name, render_csv_bytes(table))

    zip_name = f'{os.path.splitext(basename)[0]}.zip'
    return zip_buffer.getvalue(), zip_name, 'application/zip'


def build_excel_download(tables, filepath, node_id):
    """Returns `(payload_bytes, download_filename, mimetype)` for Excel."""
    if not tables:
        return None, None, None

    basename = _download_basename(filepath, node_id, '.xlsx')
    return (
        render_excel_bytes(tables),
        basename,
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    )
